SELECT MGR_EMPNO, COUNT(MGR_EMPNO) FROM CUSTOMER
GROUP BY MGR_EMPNO;

SELECT * FROM EMP;



SELECT * FROM BONUS;
TRUNCATE TABLE BONUS;


INSERT INTO Bonus (ENAME, JOB, SAL, COMM)
SELECT E.ENAME, E.JOB, E.SAL,
    CASE 
        WHEN E.JOB IN ('PRESIDENT', 'ANALYST') THEN 0
        WHEN C.CNT > 100000 THEN 2000
        ELSE 1000
    END
FROM EMP E
LEFT OUTER JOIN
    (SELECT MGR_EMPNO, COUNT(MGR_EMPNO) AS CNT 
     FROM CUSTOMER 
     GROUP BY MGR_EMPNO
    ) C
ON E.EMPNO = C.MGR_EMPNO;
