-- Synonym 실습
-- 1 scott 계정
SELECT * FROM SALGRADE;

-- 2 scott 계정 / Private synonym 생성
CREATE SYNONYM SALG FOR SALGRDE;

-- 3 System 계정
GRANT CREATE SYNONYM TO SCOTT;

-- 4 scott 계정
CREATE SYNONYM SALG FOR SALGRADE;
SELECT * FROM SALG;
DESC SALG;
SELECT * FROM TABS;
SELECT * FROM USER_OBJECTS;

-- 5 System 계정
SELECT * FROM HELP;
GRANT SELECT ON HELP TO SCOTT;
-- GRANT SELECT ON HELP TO PUBLIC;

-- 6 scott 계정
DESC HELP;
DESC SYSTEM.HELP;
SELECT * FROM SYSTEM.HELP;
-- 테이블 > Private Sysnonym > Public Synonym

-- 7 scott 계정
CREATE SYNONYM HELP FOR SYSTEM.HELP;
DESC HELP;
SELECT * FROM HELP;

