-- 0404 과제
SELECT * FROM TAB;

-- 3
-- 해당 월의 마지막 법정 영업일자를 구하는 SQL 작성
SELECT TO_CHAR(SYSDATE,'DDD'),TO_CHAR(SYSDATE,'DD'),TO_CHAR(SYSDATE,'D') FROM DUAL;
SELECT LAST_DAY(SYSDATE) FROM DUAL;

-- 답
SELECT
CASE
    WHEN TO_CHAR(LAST_DAY(SYSDATE), 'D') = 7 THEN TO_CHAR(LAST_DAY(SYSDATE)-1) -- 토
    WHEN TO_CHAR(LAST_DAY(SYSDATE), 'D') = 1 THEN TO_CHAR(LAST_DAY(SYSDATE)-2) -- 일
    ELSE TO_CHAR(LAST_DAY(SYSDATE))
    END AS "마지막 법정 영업일"
FROM DUAL;


-- 4
-- 다음 프로그래밍 방식 해결
ALTER SESSION SET NLS_DATE_FORMAT = 'RR/MM/DD';
SELECT * FROM EMP WHERE HIREDATE LIKE '82%';	-- 검색(O)
ALTER SESSION SET NLS_DATE_FORMAT = 'DD-MON-RR';
SELECT * FROM EMP WHERE TO_CHAR(HIREDATE, 'RR') = '82';	-- 날짜포맷이 변경되면 기존 검색(X)
SELECT * FROM EMP WHERE HIREDATE LIKE '%82';    -- 검색조건을 바꾸어야 검색(O)

SELECT * FROM EMP WHERE TO_CHAR(HIREDATE, 'RR') = '82';
-- 6
SELECT * FROM EMP;

SELECT DEPTNO, MAX(SAL), MIN(SAL) FROM EMP
GROUP BY DEPTNO
ORDER BY DEPTNO;

-- 7
SELECT TO_CHAR(HIREDATE, 'YYYY') AS "입사년도", MAX(SAL), MIN(SAL) FROM EMP
GROUP BY TO_CHAR(HIREDATE, 'YYYY')
ORDER BY "입사년도";

-- 8
SELECT COUNT(DECODE(DEPTNO, 10, 1)) AS "10번부서",
       COUNT(DECODE(DEPTNO, 20, 1)) AS "20번부서",
       COUNT(DECODE(DEPTNO, 30, 1)) AS "30번부서"
FROM EMP;

SELECT MAX(DECODE(DEPTNO, 10, count(*))) AS "10번부서",
       MAX(DECODE(DEPTNO, 20, count(*))) AS "20번부서",
       MAX(DECODE(DEPTNO, 30, count(*))) AS "30번부서"
FROM EMP
GROUP BY DEPTNO;

SELECT DEPTNO, COUNT(DEPTNO) FROM EMP
GROUP BY DEPTNO
ORDER BY DEPTNO;

-- 9
SELECT * FROM CUSTOMER;

SELECT * FROM CUSTOMER SAMPLE(10);
SELECT * FROM CUSTOMER SAMPLE(5) SEED(1);