-- FUNCTION
--SINGLE ROW FUNCTION
-- 1
SELECT ENAME, EMPNO, SAL, COMM FROM EMP;

-- 2
SELECT ENAME, LOWER(ENAME), UPPER(LOWER(ENAME)), LENGTH(ENAME), ABS(SAL-EMPNO), COMM
FROM EMP;

-- 3
SELECT ENAME, substr(ENAME, 1, 3) FROM EMP
WHERE HIREDATE between to_date('81/01/01', 'RR/MM/DD') and to_date('82/12/31', 'RR/MM/DD')
ORDER BY length(ENAME);

-- GROUP ROW FUNCTION
-- 4
SELECT AVG(SAL), SUM(SAL), SUM(COMM), COUNT(*) FROM EMP;

-- 5
SELECT DEPTNO, COUNT(*), SUM(SAL), AVG(SAL) FROM EMP GROUP BY DEPTNO;

-- 6
SELECT DEPTNO, JOB, COUNT(*), SUM(SAL), AVG(SAL) FROM EMP
GROUP BY DEPTNO, JOB
ORDER BY DEPTNO, JOB;