-- INSERT
DESC DEPT;
SELECT SID from v$mystat;
-- 1
INSERT INTO DEPT VALUES(50,'연구소1','서울');

-- 2
INSERT INTO DEPT(DEPTNO, DNAME, LOC) VALUES(51, '연구소2', '대전');

-- 3
SELECT * FROM DEPT;

-- 4
INSERT INTO DEPT VALUES('중부영업점', '대구');

-- 5
INSERT INTO DEPT(DNAME, LOC) VALUES('중부영업점', '대구');

-- 6
INSERT INTO DEPT(DNAME, LOC) VALUES('중부지점', '대구');

-- 7-1
INSERT INTO DEPT(DEPTNO, DNAME, LOC) VALUES(52, '북부지점', NULL);

-- 7-2
INSERT INTO DEPT(DEPTNO, DNAME, LOC) VALUES(53, '남부지점', '');

-- 8
INSERT INTO DEPT(DEPTNO, DNAME) VALUES(54, '서부지점');

-- 9
SELECT DEPTNO, DNAME, NVL(LOC, '미지정지역') AS LOC FROM DEPT;

-- 10
COMMIT;